# this docker-compose works with TestSolution that use sql server db
services:
  database:
    image: mcr.microsoft.com/mssql/server:2022-CU8-ubuntu-20.04
    restart: always
    environment:
      MSSQL_SA_PASSWORD: ${SQLSERVER_PASSWORD:?database password not set}
      ACCEPT_EULA: Y
  #  volumes:
  #    - sqlserver-data:<path>
  cloud_beaver:
    image: dbeaver/cloudbeaver
    restart: always
    ports:
      - 8080:8978
    depends_on:
      - database
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: runtime
      args:
        - build_container=mcr.microsoft.com/dotnet/sdk:7.0
        - runtime_container=mcr.microsoft.com/dotnet/aspnet:7.0
    ports:
      - 5000:80
    depends_on:
      - database
    environment:
      ConnectionStrings__TestSystemContext: ${SQLSERVER_CONNECTIONSTRING:?db connection string not set}

volumes:
 sqlserver-data:
