name: ci

env:
  BUILD_CONTAINER: mcr.microsoft.com/dotnet/sdk:7.0
  RUNTIME_CONTAINER: mcr.microsoft.com/dotnet/aspnet:7.0

on:
  push:
    branches:
      - "main"
  pull_request: 
    branches:
      - "main"
  workflow_dispatch: 
    
jobs:
  test_and_lint:
    uses: ./.github/workflows/test-and-lint.yml
    with:
      solution-file: ./src/TestSystem.sln
      container: ${{ vars.BUILD_CONTAINER}}

  build:
    runs-on: ubuntu-latest
    needs: test_and_lint
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/test-system:latest
          build-args: |
            build_container=${{ env.BUILD_CONTAINER}}
            runtime_container=${{ env.RUNTIME_CONTAINER}}