name: 'test and lint'

on:
  workflow_call: 
    inputs:
      container:
        type: string
        required: true
        description: 'Image where workflow will run'
      solution-file:
        type: string
        description: '.sln file path'
        required: true
    
jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: ${{ inputs.container }}
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: dotnet test
        run: dotnet test ${{ inputs.solution-file }} --collect:"XPlat Code Coverage" --results-directory coverage
      -
        name: ReportGenerator
        uses: danielpalme/ReportGenerator-GitHub-Action@5.1.26
        with:
          reports: coverage/*/coverage.cobertura.xml
          targetdir: coveragereport
          reporttypes: MarkdownSummaryGithub;Badges
          assemblyfilters: -*.Database.*;-*.Tests
          tag: '${{ github.run_number }}_${{ github.run_id }}'
      -
        name: Write to Job Summary
        if: ${{ always() }}
        run: cat coveragereport/SummaryGithub.md >> $GITHUB_STEP_SUMMARY

  lint:
    runs-on: ubuntu-latest
    container:
      image: ${{ inputs.container }}
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: dotnet lint
        run: dotnet format ${{ inputs.solution-file }} --verify-no-changes
    